apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
type: Opaque
data:
  ATLAS_URI: bW9uZ29kYitzcnY6Ly90ZXN0dXNlcjp0ZXN0dXNlcjEyM0Bub3Rlc2FwcC5yYm1mb2xhLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1ub3Rlc2FwcA== 
  ACCESS_TOKEN_SECRET: NWI4NWJmZjgzNmM4YmZhNmEyYWZjZmExMjZjNmFhNDUwNmQyNTQzZDk5YWVjZGM3ZDhiZTdkMWQyMzBjMDZkYw==
# (echo -n "uri" | base64`)
  