version: '3.5'
services:
  frontend:
    build:
      context: ../frontend/notes
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=${ATLAS_URI}
      - NODE_ENV=deploy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge