apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: vidhuarora/my-backend:latest (or use `my-backend:latest` if not pushing to a registry)
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_URI
          value: ${ATLAS_URI} 
        - name: NODE_ENV
          value: "deploy"
        - name: ACCESS_TOKEN_SECRET
          value: ${ACCESS_TOKEN_SECRET} 