apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: vidhuarora/my-frontend:latest (or `my-frontend:latest`)
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          value: "http://backend-service:8000"
        - name: VITE_BASE_URL
          value: "http://localhost:8000" 
        - name: NODE_ENV
          value: "deploy"